Fixing NameError: global name 'options' is not defined.
if chrome_options is not None:

...
py/selenium/webdriver/chrome/webdriver.py", line 55, in __init__
   desired_capabilities.update(options.to_capabilities())
NameError: global name 'options' is not defined

Regression was introduced in 6a7bb83aaea4a69d6de03caddb81c9a7eb11c4b7

Cr-Mirrored-From: https://chromium.googlesource.com/external/github.com/SeleniumHQ/selenium
Cr-Mirrored-Commit: df140408a58ac6d45fe56ab207c03ab4ef86174a